theme = "kanagawa-nbg"

[editor]
line-number = "relative"
mouse = false
rulers = [80]
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true

[keys.normal]
D = "@vgld"

[keys.normal." "]
"=" = ":format"
f = "file_picker_in_current_directory"
F = "file_picker"
e = "file_explorer_in_current_directory"
