theme = "kanagawa-nbg"

[editor]
line-number = "relative"
mouse = false
rulers = [100]

[keys.normal]
D = "@vgld"

[keys.normal." "]
"=" = ":format"
f = "file_picker_in_current_directory"
F = "file_picker"
e = "file_explorer_in_current_directory"
