
[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "zig"
auto-format = false

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "\t" }

[[langauge]]
name = "typst"
soft-wrap.enable = true

[language-server.tinymist]
command = "tinymist"
config.preview.background.enabled = true
config.preview.background.args = [
  "--data-plane-host=127.0.0.1:8080", "--invert-colors=never", "--open"]

